name: wasfa
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  google_fonts: ^4.0.3
  nb_utils: ^5.0.8
  top_snackbar_flutter: ^3.0.0+1

dev_dependencies:
  flutter_native_splash: ^2.2.18
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/splash.png
  android: true

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images\medical.png 
    - images\doctor.png 
    - images\pharmacy.png 
    